#!/bin/bash
###################################################################
# Script Name	  : merge2.sh
# Description	  : Generates PCA when teh reference population was changed.
# Args          : PLINK file prefix
# Author        : Milind Agarwal
# Lab           : Markle Lab, JHBSPH
# Email         : magarw10@jhu.edu
###################################################################


INFILE=$1

# First, we need to check if a global PCA has been done or not, this will drastically increase performance since we can reuse intermediate files.
#
# if [[ -f ./Datasets/ancestry_data/chr1-4_extr.bed && -f ./Datasets/ancestry_data/chr1-4_extr.bim && -f ./Datasets/ancestry_data/chr1-4_extr.fam && -f ./Datasets/ancestry_data/chr5-8_extr.bed && -f ./Datasets/ancestry_data/chr5-8_extr.bim && -f ./Datasets/ancestry_data/chr5-8_extr.fam && -f ./Datasets/ancestry_data/chr9-X_extr.bed && -f ./Datasets/ancestry_data/chr9-X_extr.bim  && -f ./Datasets/ancestry_data/chr9-X_extr.fam ]]; then
# 	echo "All 9 extracted reference files exist"
# else
# 	echo "Atleast 1/9 file wasn't found. So, we'll recreate the extracted binaries."

if [[ -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr1-4_extr.bed && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr1-4_extr.bim && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr1-4_extr.fam && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr5-8_extr.bed && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr5-8_extr.bim && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr5-8_extr.fam && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr9-X_extr.bed && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr9-X_extr.bim  && -f ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr9-X_extr.fam ]]; then
	echo "All 9 extracted reference files exist"
else
	echo "Atleast 1/9 file wasn't found. So, we'll recreate the extracted binaries."


	## First, we need to use the common markers generated by the python script
	## to extract the markers in sample from all three reference files.

	INFILE=$1

	# ./plink/plink --bfile ./Datasets/ancestry_data/chr1-4 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr1-4_extr
	# ./plink/plink --bfile ./Datasets/ancestry_data/chr5-8 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr5-8_extr
	# ./plink/plink --bfile ./Datasets/ancestry_data/chr9-X --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr9-X_extr

	./plink/plink --bfile ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr1-4 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr1-4_extr --memory 12000
	./plink/plink --bfile ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr5-8 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr5-8_extr --memory 12000
	./plink/plink --bfile ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr9-X --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr9-X_extr --memory 12000

fi
# Need to make sure THAT COMMON MARKERS IS A FILE THAT EXISTS EVEN IF I RUN THIS FIRST..
# At this stage, we have common SNP marker extracted files.

# Next, we need to KEEP the individuals from our filter_me txt output depending on the user's input checkbox selections on the webpage.
./plink/plink --bfile ./temp/ancestry_buffer/chr1-4_extr --keep ./data/filter_me.txt --make-bed --out ./temp/ancestry_buffer/chr1-4_extr_pop --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr5-8_extr --keep ./data/filter_me.txt --make-bed --out ./temp/ancestry_buffer/chr5-8_extr_pop --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr9-X_extr --keep ./data/filter_me.txt --make-bed --out ./temp/ancestry_buffer/chr9-X_extr_pop --memory 12000


## Then, we will attempt to merge these reduced files one by one.
./plink/plink --bfile ./temp/ancestry_buffer/chr1-4_extr_pop --bmerge ./temp/ancestry_buffer/chr5-8_extr_pop.bed ./temp/ancestry_buffer/chr5-8_extr_pop.bim ./temp/ancestry_buffer/chr5-8_extr_pop.fam --make-bed --out ./temp/ancestry_buffer/chr1-8_extr_pop --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr1-8_extr_pop --bmerge ./temp/ancestry_buffer/chr9-X_extr_pop.bed ./temp/ancestry_buffer/chr9-X_extr_pop.bim ./temp/ancestry_buffer/chr9-X_extr_pop.fam --make-bed --out ./temp/ancestry_buffer/chr1-X_extr_pop --memory 12000

## USE BASH IF THEN STATMENTS---- UP---I should probably build in functionality in the above merges for handling merge MISSNP failures.

## Next, we will try to merge the sample with the reference...
./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr_pop --bmerge "${INFILE}.bed" "${INFILE}.bim" "${INFILE}.fam" --make-bed --out ./temp/ancestry_buffer/merge --memory 12000
./plink/plink --bfile $INFILE --flip ./temp/ancestry_buffer/merge-merge.missnp --make-bed --out "${INFILE}_flip" --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr_pop --bmerge "${INFILE}_flip.bed" "${INFILE}_flip.bim" "${INFILE}_flip.fam" --make-bed --out ./temp/ancestry_buffer/merge2 --memory 12000

./plink/plink --bfile "${INFILE}_flip" --exclude ./temp/ancestry_buffer/merge2-merge.missnp --make-bed --out "${INFILE}_flip_exclude" --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr_pop --exclude ./temp/ancestry_buffer/merge2-merge.missnp --make-bed --out ./temp/ancestry_buffer/chr1-X_extr_pop_exclude --memory 12000

## Reattempt the merge

if [[ -f  "${INFILE}_flip_exclude.bed" &&  -f "${INFILE}_flip_exclude.bim" && -f  "${INFILE}_flip_exclude.fam" ]]; then
	echo "All three files exist"
	./plink/plink -bfile ./temp/ancestry_buffer/chr1-X_extr_pop_exclude --bmerge "${INFILE}_flip_exclude.bed" "${INFILE}_flip_exclude.bim" "${INFILE}_flip_exclude.fam" --make-bed --out ./temp/ancestry_buffer/merge3 --memory 12000

else
	echo "One of thee three doesn't exist :/"
	./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr_pop_exclude --bmerge "${INFILE}_flip.bed" "${INFILE}_flip.bim" "${INFILE}_flip.fam" --make-bed --out ./temp/ancestry_buffer/merge3 --memory 12000
fi

./plink/plink --bfile ./temp/ancestry_buffer/merge3 --pca --out ./temp/ancestry_buffer/merge3_pca --memory 12000
