#!/bin/bash

###################################################################
# Script Name	  : merge.sh
# Description	  : Generates PCA when the reference population was unchanged.
# Args          : PLINK file prefix
# Author        : Milind Agarwal
# Lab           : Markle Lab, JHBSPH
# Email         : magarw10@jhu.edu
###################################################################



## First, we need to use the common markers generated by the python script
## to extract the markers in sample from all three reference files.

INFILE=$1

# ./plink/plink --bfile ./Datasets/ancestry_data/chr1-4 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr1-4_extr
# ./plink/plink --bfile ./Datasets/ancestry_data/chr5-8 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr5-8_extr
# ./plink/plink --bfile ./Datasets/ancestry_data/chr9-X --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr9-X_extr

./plink/plink --bfile ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr1-4 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr1-4_extr --memory 12000
./plink/plink --bfile ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr5-8 --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr5-8_extr --memory 12000
./plink/plink --bfile ../../../webseq_sandbox/SNP_Analysis_Reference_Data/ancestry_data/chr9-X --extract ./data/common_markers.txt --make-bed --out ./temp/ancestry_buffer/chr9-X_extr --memory 12000

## Then, we will attempt to merge these reduced files one by one.
./plink/plink --bfile ./temp/ancestry_buffer/chr1-4_extr --bmerge ./temp/ancestry_buffer/chr5-8_extr.bed ./temp/ancestry_buffer/chr5-8_extr.bim ./temp/ancestry_buffer/chr5-8_extr.fam --make-bed --out ./temp/ancestry_buffer/chr1-8_extr --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr1-8_extr --bmerge ./temp/ancestry_buffer/chr9-X_extr.bed ./temp/ancestry_buffer/chr9-X_extr.bim ./temp/ancestry_buffer/chr9-X_extr.fam --make-bed --out ./temp/ancestry_buffer/chr1-X_extr --memory 12000

## USE BASH IF THEN STATMENTS---- UP---I should probably build in functionality in the above merges for handling merge MISSNP failures.

## Next, we will try to merge the sample with the reference...
./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr --bmerge "${INFILE}.bed" "${INFILE}.bim" "${INFILE}.fam" --make-bed --out ./temp/ancestry_buffer/merge --memory 12000
./plink/plink --bfile $INFILE --flip ./temp/ancestry_buffer/merge-merge.missnp --make-bed --out "${INFILE}_flip" --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr --bmerge "${INFILE}_flip.bed" "${INFILE}_flip.bim" "${INFILE}_flip.fam" --make-bed --out ./temp/ancestry_buffer/merge2 --memory 12000

./plink/plink --bfile "${INFILE}_flip" --exclude ./temp/ancestry_buffer/merge2-merge.missnp --make-bed --out "${INFILE}_flip_exclude" --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr --exclude ./temp/ancestry_buffer/merge2-merge.missnp --make-bed --out ./temp/ancestry_buffer/chr1-X_extr_exclude --memory 12000

## Reattempt the merge
./plink/plink --bfile ./temp/ancestry_buffer/chr1-X_extr_exclude --bmerge "${INFILE}_flip_exclude.bed" "${INFILE}_flip_exclude.bim" "${INFILE}_flip_exclude.fam" --make-bed --out ./temp/ancestry_buffer/merge3 --memory 12000
./plink/plink --bfile ./temp/ancestry_buffer/merge3 --pca --out ./temp/ancestry_buffer/merge3_pca --memory 12000
